### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by quinnzbellz** [quinnzbellz/LinuxDoomLauncher#3]
These are some things I'd like to accomplish with the launcher. Please add any suggestions and other things below.

### Todo
- [ ] Work on Flatpak Version
  - [ ] Create seperate branch with support for GZDoom Flatpak (so that it'll work on the steam deck)
- [ ] Change Select PK3 buttons to list with add file
- [ ] Add directory in .config for storing pk3's, pwads, and config files
  - [ ] Implement support for config files
- [ ] #4
- [X] Add GZDoom Executable Selector

#### Todo Later
- [ ] Create website for the project
- [ ] Add Raze Support
